spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://0.0.0.0:27017/productdb
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0